### ISSUE TITLE
Update inpycon/init.sls

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/magudi#30]
Since magudi uses letsencrypt live certs so the symlink rules for the old certs can be removed. It gives a warning now while running provision. Relevant code https://github.com/pythonindia/magudi/blob/6fd3069be580df8c4a3b85bb1e9c216a3d7e2594/salt/roots/inpycon/init.sls#L106-L112

**Comment by palnabarun** [comment]
What is the exact error?

**Comment by ananyo2012** [comment]
```
----------
          ID: /etc/ssl/in.pycon.org.2016.fullchain.pem
    Function: file.managed
      Result: False
     Comment: Unable to manage file: File or directory does not exist.
     Started: 12:50:06.214218
    Duration: 21.052 ms
     Changes:   
    Warnings: Failed to detect changes to file: Failed to read
              /etc/letsencrypt/live/in.pycon.org-0001/fullchain.pem: No such
              file or directory
----------
          ID: /etc/ssl/in.pycon.org.2016.pvtkey.pem
    Function: file.managed
      Result: False
     Comment: Unable to manage file: File or directory does not exist.
     Started: 12:50:06.235999
    Duration: 5.222 ms
     Changes:   
    Warnings: Failed to detect changes to file: Failed to read
              /etc/letsencrypt/live/in.pycon.org-0001/privkey.pem: No such file
              or directory
```
